### ISSUE TITLE
Latest update broke the theme

### ISSUE THREAD

**Issue by m1keil** [Miw0/SoDaReloaded-Theme#11]
Hey,
My sublime just went crazy after the last theme update. Totally broken.

![preferences sublime-settings cloudify-nodecellar-example-master 2015-09-29 18-05-37](https://cloud.githubusercontent.com/assets/1589008/10168259/b867a356-66d4-11e5-932d-8f34a4030b82.png)

Tried reinstalling the theme, got same results. Soda theme works.

**Comment by michael-jahn-dev** [comment]
Hey,

did you try to restart Sublime Text? And if this did not work, try to reinstall the theme (remove and install again).  

Because I added a light variant all paths are different now. 

Hope this helps, if not I will have a look tomorrow. 
Sorry for the inconvenience.

**Comment by m1keil** [comment]
Hey,
thanks for the response. 

Yep tried the usual restart sublime, re-install theme and even tried the light version instead. 
I wonder if there's some error log I can check...

**Comment by m1keil** [comment]
Sorry, tried the whole remove/install cycle again just in case and now it seems like it did the trick.
Thanks!

**Comment by michael-jahn-dev** [comment]
No problem, good to hear that it worked out well ;)

**Comment by daniel-liuzzi** [comment]
I am experiencing the same issue on Windows 10 Pro. Unfortunately, removing and re-installing the theme did not work for me. Restoring a backup of my settings directory from last week fixes it, but as soon as the theme is updated, everything breaks again the next the I open Sublime Text.

![sublime text 3](https://cloud.githubusercontent.com/assets/143884/10221008/ad64d85c-684b-11e5-97c1-b519da808efc.png)

**Comment by daniel-liuzzi** [comment]
I figured it out. In v1.0.0 the theme name [changed](https://github.com/Miw0/sodareloaded-theme/commit/5246137e1422542a5d011b1deb63e49cd4ec23cd#diff-6cc7267ed192eff9a24ce03e3c0abe75) from `SoDaReloaded` to `SoDaReloaded Dark`, as @Miw0 [comments above](https://github.com/Miw0/sodareloaded-theme/issues/11#issuecomment-144096536). **There is no need to reinstall the theme.** To fix, follow the steps below:
1. Go to _Preferences_ -> _Settings &ndash; User_ 
2. Locate the following line:
   
   ``` json
   "theme": "SoDaReloaded.sublime-theme"
   ```
3. Change it as follows:
   
   **Dark variant**
   
   ``` json
   "theme": "SoDaReloaded Dark.sublime-theme"
   ```
   
   **Light variant**
   
   ``` json
   "theme": "SoDaReloaded Light.sublime-theme"
   ```
4. Save

Changes take effect immediately; I did not even need to restart Sublime Text.

**Comment by m1keil** [comment]
oohhh.... yea that might explain it.

**Comment by michael-jahn-dev** [comment]
Oh yea well you're right, my fault. 
Good to hear that it works now and many thanks to @dliuzzi to point that out :)
