### ISSUE TITLE
Sidebar does not change after restart

### ISSUE THREAD

**Issue by rkpatel33** [Miw0/SoDaReloaded-Theme#13]
My sidebar does not update to the the SodaReloaded theme even after a restart. Any ideas on why this would be? I have a feeling it might be a non-SodaReloaded issue.

https://www.evernote.com/l/AArG-WnGWZ9O1IJ9pn1Qxte-P-eMpN9uCf4

**Comment by michael-jahn-dev** [comment]
Please see #11 
If that doesn't fix it, I'll have a look.

**Comment by rkpatel33** [comment]
I figured out that I had two entries in user settings for the theme, the second set it to default. I did not realize it because I also did not realize ST3 was alphabeticaly reordering settings keys and removing comments, in the process it was choosing the last occurrenc of the key as the intended value and tossign the earlier one.

**Comment by michael-jahn-dev** [comment]
Good to hear that you could solve the problem :)
