### ISSUE TITLE
Classic rounded tabs work, perhaps document?

### ISSUE THREAD

**Issue by adrinux** [Miw0/SoDaReloaded-Theme#17]
I was wondering if this theme supported rounded tabs like the original soda, so tried the classic tabs setting - it works!
Just added the following to my user preferences:

```
"soda_classic_tabs": true,
```

May or may not be worth mentioning on the home page.

**Comment by michael-jahn-dev** [comment]
Thanks @adrinux for pointing this out. I updated the README :) See https://github.com/Miw0/SoDaReloaded-Theme/blob/master/README.md#user-content-want-to-use-soda-classic-tabs
