### ISSUE TITLE
Regarding icon for git files

### ISSUE THREAD

**Issue by gtr32x** [Miw0/SoDaReloaded-Theme#18]
I'd like to say thanks for the continual support of the Soda theme and I love it!

I would like to ask if it's possible to set icons on the file navigation bar for git related files like .gitignore? I've seen other themes doing it and I thought that would be a great addition.

**Comment by michael-jahn-dev** [comment]
Nice to hear that you like it :)

Sure that would be possible. Could you give me  an example of a theme which does that?

**Comment by gtr32x** [comment]
Hi there,

Yes, an example of it could be found in https://packagecontrol.io/packages/Material%20Theme

**Comment by michael-jahn-dev** [comment]
Sorry @gtr32x but I am really busy at the moment and don't have time to look at this feature. Any help would be appreciated!

**Comment by michael-jahn-dev** [comment]
@gtr32x GIT files work since I updated the Icons from Seti_UI, I'm gonna close this now.
