### ISSUE TITLE
Tab AutoWidth

### ISSUE THREAD

**Issue by gj1118** [Miw0/SoDaReloaded-Theme#20]
Hi, 
This is not a bug but rather a feature request. Few themes like the material theme have a feature (exposed via settings) to make sure that the width of the tabs auto fits its contents. an example follows (taken from the material theme)

```
"material_theme_tabs_autowidth"           : true , // Enable autowidth for tabs
```

Can you please incorporate this feature ? 

Thanks and Regards
Gagan

**Comment by gj1118** [comment]
I think if you add 

``` json
  {
    "class": "tabset_control",
    "settings": ["soda_tabs_autowidth"],
    "tab_width": 0
  },
```

to your theme file (both light and dark), it should work. The user would then need to set 

```
"soda_tabs_autowidth" : true
```

in his/her user preferences to set the autowidth option 

If this does not work, please let me know. 

thanks

**Comment by michael-jahn-dev** [comment]
Thanks alot @gj1118 !
