### ISSUE TITLE
Icon requests for: YAML files and Dockerfile

### ISSUE THREAD

**Issue by nickjj** [Miw0/SoDaReloaded-Theme#21]
Your initial icons are quite nice, but currently it renders default icons for both `.yml` files and `Dockerfile`. Any ideas for creating custom icons for these file types?

The Docker one could draw inspiration from their official logo, but I'm not so sure about YAML.

**Comment by michael-jahn-dev** [comment]
Hey @nickjj I just pushed an update of the Seti_UI icons which this theme uses. I guess there are also YAML and Dockerfile icons included :)

**Comment by nickjj** [comment]
Excellent, just upgraded and noticed them. They are good. Thanks @Miw0.

**Comment by michael-jahn-dev** [comment]
You're welcome :)

Von meinem iPhone gesendet
