### ISSUE TITLE
Syntaxes included with this package conflict with other syntaxes

### ISSUE THREAD

**Issue by gabrielecirulli** [Miw0/SoDaReloaded-Theme#23]
I use the SCSS syntax bundled with https://packagecontrol.io/packages/SCSS to get SCSS highlighting. SoDaReloaded-Theme seems to include a custom version of this syntax that somehow always overrides the other one, no matter whether it's set as default or not.

The SCSS syntax bundled with this package doesn't actually highlight code correctly.

I would suggest removing these syntax bundles or at least finding a way not to make them override the normal one, as this proves to create an annoying behaviour with Sublime Text not being able to tell which package to keep active.

**Comment by gabrielecirulli** [comment]
I temporarily fixed this by using https://packagecontrol.io/packages/Extract%20Sublime%20Package, extracting the contents of this package, deleting the original `.sublime-package`, removing the syntax files from `dark/icons/Langs` and `light/icons/Langs`.

**Comment by michael-jahn-dev** [comment]
@gabrielecirulli Hold on, I will have a look into this as fast as I can! Thanks for reporting and pointing out a fix! :)

**Comment by gabrielecirulli** [comment]
Thanks for your responsiveness! I appreciate your work :)

**Comment by michael-jahn-dev** [comment]
@gabrielecirulli I found a fix. The `tmLanguage` files were overriding all Sass, SCSS and Less file syntaxes with the syntax for CSS which is the reason for showing you CSS syntax highlighting in those files. This has been fixed. Can you test this on the master branch? When this fixes your issue I will release a new version :)

**Comment by gabrielecirulli** [comment]
Sounds great, thanks! Do I just have to install the contents of the master branch into my Sublime packages folder?

**Comment by gabrielecirulli** [comment]
Well I guess I just answered my question by myself, there doesn't seem to be a build process :)

**Comment by michael-jahn-dev** [comment]
Yes @gabrielecirulli you just have to git clone or download it manually it into your Packages folder and rename it to `Theme - SoDaReloaded`. Be sure to deinstall the package through Package Control first.

**Comment by brownoxford** [comment]
I'm seeing a similar issue with .pp files and Puppet syntax highlighting. I have the SublimePuppet package installed, and have opted to "open all with current extension as" using the Puppet syntax from that package, but the syntax from SoDaReloaded always overrides it.

**Comment by michael-jahn-dev** [comment]
Thanks for reporting this @brownoxford. I guess this is the same issue. What file endings Puppet files could have? I will fix this in the language file.

**Comment by brownoxford** [comment]
@Miw0, *.pp

**Comment by michael-jahn-dev** [comment]
I'm gonna close this issue for now and release a new version. Thanks for reporting!

**Comment by timelordx** [comment]
Any update on this? I thought I have been going crazy for more than a year now, when all my Puppet (*.pp) files lost their syntax highlighting. I've been rewriting Sublime configs, reinstalling Sublime, reinstalling the whole OS, and still the same issue as described above by @brownoxford 

I somehow stumbled upon this thread here just today, and after I uninstalled SoDaReload, Puppet syntax highlighting works again \o/ I love SoDaReloaded, but I need Puppet syntax highlighting more than a VERY nice theme :( 

Any ideas when this could be fixed please? I was running the latest Sublime Text 3 with SoDaReloaded v1.3.0 via Package Control.

**Comment by timelordx** [comment]
I've tried SoDaReloaded via Package Control as well as from here via git, still the same result. As soon as the SoDaReloaded is installed, the following files are created, and from that moment Puppet syntax highlighting doesn't work:
```
~/Library/Application Support/Sublime Text 3/Cache/Theme - SoDaReloaded/settings/langs/Puppet.tmLanguage.cache
~/Library/Application Support/Sublime Text 3/Cache/Theme - SoDaReloaded/settings/langs/Puppet.tmLanguage.rcache
```

**Comment by timelordx** [comment]
One more post :)

I have deleted the following two files:
```
~/Library/Application Support/Sublime Text 3/Packages/Theme - SoDaReloaded/settings/prefs/icon_puppet.tmPreferences 
~/Library/Application Support/Sublime Text 3/Packages/Theme - SoDaReloaded/settings/langs/Puppet.tmLanguage
```
and everything works great now. I have Sublime Text with SoDaReload theme, and Puppet syntax highlighting works great via [SublimePuppet](https://github.com/russCloak/SublimePuppet) package. I'm happy \o/
