### ISSUE TITLE
Integrate Solarized versions of this theme

### ISSUE THREAD

**Issue by gj1118** [Miw0/SoDaReloaded-Theme#28]
Hi, Can you please incorporate this theme https://github.com/jrolfs/sodarized as well with your theme? So instead of the current two (light and dark ) , you would have light , dark , solarized light and dark as well. Since both of them are based on soda theme having them together as one makes sense. 

Please let me know what you think. 
Thanks and Regards
G

**Comment by gj1118** [comment]
Hi , I have made changes related to this request. the changes included sodarized theme changes , as well as a custom color scheme. Since, I have never worked with creating pull requests on git/github. I am attaching file here. 

[SoDaReloaded-Theme.zip](https://github.com/Miw0/SoDaReloaded-Theme/files/310852/SoDaReloaded-Theme.zip)

**Comment by michael-jahn-dev** [comment]
Hey @gj1118 did you do the changes by yourself or did you copy them from the package you noted above? I don't want to run into License issues here. 
Anyway I'm gonna review the changes you made and think about whether I should merge them or not. Does anyone else see the needs of a Solarized version of this theme?

Btw, you can read how to do forks/pull requests here: 
https://help.github.com/articles/fork-a-repo/
https://help.github.com/articles/creating-a-pull-request/

**Comment by gj1118** [comment]
Well TBH , I did copy and then modified the sodarized theme as per what you had done for the current light and dark versions. 

I am somewhat sure that I am allowed to do so. I am saying this because the sodaried theme itself is a derivative work from the original "Theme - Soda " by Ian Hill . I also verified that the license terms for the SodaRized theme is the same as the original theme, which is why I am guessing it should be good to go. 

Let me know if you have any concerns. I am not a lawyer myself, so if if you think its not good for public consumption - drop this issue. 

Thanks and Regards
G

**Comment by michael-jahn-dev** [comment]
Hey @gj1118,

I like your idea of having a solarized version of this theme so I created a branch to be able to work on this feature (see https://github.com/Miw0/SoDaReloaded-Theme/tree/solarized). I added your changes and will do some more work to keep consistency and release a v2.0.0 as soon as I am finished.

Thanks for your contriubutions! :+1:

**Comment by gj1118** [comment]
Thank you sir. 

FYI, There is also a custom light color scheme "HarneetIsAwesome" that you would find in the zipped file . When you are reviewing the scheme , can you please review it as well. It is a fork of Tomorrow light color scheme. Would really appreciate , if it made the release as well. 

Thanks 
Gagan

**Comment by michael-jahn-dev** [comment]
To be honest I wouldn't go for including a color scheme in this package as I didn't include any for the other 2 theme versions yet.
I could offer you to feature it in the README as I did with the Bubububububad and Boneyfied Color Schemes. Is that okay for you?

**Comment by gj1118** [comment]
That is an extremely generous offer but I would like to politely and respectfully turn it down  for the following reason.. 

When I install a theme , I usually do not like to go back again to Package Control and install a color scheme. I would also not like to muddy your readme file with links to a color scheme that some devs might not like  :) . For these reasons I would like to opt out.

Sorry about that Sir and Thank you for the offer. That was indeed very nice of you. 

Thanks and Regards
Gagan

**Comment by michael-jahn-dev** [comment]
Okay as you wish :)

I'm gonna close this now because we have a branch for this feature. Thank you for contributing @gj1118 I really appreciate that!
