### ISSUE TITLE
Please add support for st-file-icons

### ISSUE THREAD

**Issue by gj1118** [Miw0/SoDaReloaded-Theme#30]
can you please add support for st-file-icons ?
https://github.com/oivva/st-file-icons

**Comment by tomm1996** [comment]
https://github.com/ihodev/a-file-icon

> ### Bring Support of the File Icon Customization to Your Theme
> If you are a theme developer and you want to support a file icon customization, you should:
> - Remove all stuff related to the icon setup: .tmPreferences, .sublime-settings, .sublime-syntax and .tmLanguage files.

Correct me if I'm wrong but that does not sound like the Theme will be compatible with installations without a-file-icon.
