### ISSUE TITLE
Release a new version?

### ISSUE THREAD

**Issue by unnawut** [Miw0/SoDaReloaded-Theme#37]
Hey everyone.

Thank you for your great work on the package. Will buy you a beer within this week :)

The latest release was well over 1.5 years ago (v1.3.0 on May 24 2016 according to [GitHub's releases](https://github.com/Miw0/SoDaReloaded-Theme/releases)). I install this theme via [Package Control which has v1.3.0](https://packagecontrol.io/packages/Theme%20-%20SoDaReloaded). It would be super great to have a more recent code version there.

Could you release a new version that has a more recent codebase? Thanks!

**Comment by michael-jahn-dev** [comment]
Hey,
sure. I will release a new version as soon as I get back to work after new years day.

**Comment by unnawut** [comment]
Hey @Miw0, looking from [GH releases](https://github.com/Miw0/SoDaReloaded-Theme/releases) and [PackageControl](https://packagecontrol.io/packages/Theme%20-%20SoDaReloaded), I don't think a new version has been released yet...
