### ISSUE TITLE
Caret next to folder

### ISSUE THREAD

**Issue by wguldin** [Miw0/SoDaReloaded-Theme#6]
Hi,

I was wondering what the proper customization would be to get a caret next to the folder name in the sidebar? Thanks, and a great theme!

**Comment by michael-jahn-dev** [comment]
Hey,

I have replaced the caret icon with the folder icon so you need to fork the repo and edit it by yourself.

Have a look at the following lines, it shouldn't be that hard :)
https://github.com/Miw0/sodareloaded-theme/blob/master/SoDaReloaded.sublime-theme#L687

I hope I could help and thanks for the compliment :)
