### ISSUE TITLE
Sidebar left margin

### ISSUE THREAD

**Issue by robertrichard** [Miw0/SoDaReloaded-Theme#8]
Hi,

Nice work getting a nice set of icons working with the Soda Theme. Any chance  to get items closer to the left edge within the sidebar? If so, what do I need to do to customize the theme? That's some precious sidebar real estate, particularly when working with a deep file structure.

Best,

**Comment by michael-jahn-dev** [comment]
Hey,

thanks alot :)

I had a hard time aligning the sidebar with the left edge until it worked out nicely. You could try to change some values in the Sublime-Theme-File (see here https://github.com/Miw0/sodareloaded-theme/blob/master/SoDaReloaded%20Dark.sublime-theme#L550 (and of course also the light version)).

If you were able to get this done nicely, feel free to post a screenshot and/or a pull request and maybe I can merge this into the package.

Cheers
