### ISSUE TITLE
Light Variant

### ISSUE THREAD

**Issue by pradyunsg** [Miw0/SoDaReloaded-Theme#9]
Hi!

Could you please create a light variant for this theme? I really like the idea but as I currently use 2 different colour-schemes (light/dark) as per the room lighting, the lack of a light variant hurts.

**Comment by michael-jahn-dev** [comment]
Hey,

sure I'm on it ;)

**Comment by michael-jahn-dev** [comment]
@pradyunsg see the master branch for the light variant. The icons seem to be a bit too bright for the light version, do you have an idea where I can get better icons?

**Comment by pradyunsg** [comment]
I'll look into it. If needed, I'll modify the existing ones for it...

But that's if and when I get some free time this evening.

**Comment by michael-jahn-dev** [comment]
Yea sure would be nice though :)

**Comment by pradyunsg** [comment]
Bazinga! (Because I sounded too formal. :stuck_out_tongue:)

**Comment by pradyunsg** [comment]
Nope, I won't be able to do this today. 

Well, if you have [GIMP](http://gimp.org/) installed, you should be able to make the relavant changes through the Hue-Saturation tool. http://docs.gimp.org/en/gimp-tool-hue-saturation.html

**Comment by pradyunsg** [comment]
Whoops!

**Comment by michael-jahn-dev** [comment]
@pradyunsg Do you know how I can use different icons for the two variants? Honestly I have no idea how to configure that..

**Comment by pradyunsg** [comment]
One way would be to place the two theme files in separate folders and have icon folders in them.

Like:

```
Theme - SoDaReloaded/
    light/
        icons/
        SoDaReloaded Light.sublime-theme
    dark/
        icons/
        SoDaReloaded Dark.sublime-theme
```

As long as you don't change the name of the theme file, it'll work just fine. Also, I recommend putting the "dark" and "light" folders into a "themes" folder. (From issue 32 @ sublimehq/Packages, because I don't want to link that issue here.)

**Comment by michael-jahn-dev** [comment]
Ahh I see. I didn't move the `.sublime-theme` Files into the folders that's why it didn't work for me.
Hm I don't see any benefit to add another folder-level. Also they say that adding subdirectories will remove noise and I think we don't have too many files so it is not disturbing and unorganized :)

**Comment by michael-jahn-dev** [comment]
Btw I made a new branch for this enhancement, see https://github.com/Miw0/sodareloaded-theme/tree/light-variant-icons

**Comment by pradyunsg** [comment]
That's true.

I'll see this once I get better... (I fell ill today :confused:)

**Comment by pradyunsg** [comment]
I didn't get well. :/

Great to see that this is released! :smile:

Just one thing, you forgot to update the screen-shot of the light variant in the readme, with the newer icons.

**Comment by michael-jahn-dev** [comment]
Well I guess you misunderstood something :) I just made a new branch and moved things to the correct place. I didn't have time to make new icons yet..

**Comment by michael-jahn-dev** [comment]
Closing this now because the Light variant is working and released. I made a new issue for the icons, see #14

**Comment by pradyunsg** [comment]
Ah well. I did. :stuck_out_tongue:
